title: Rina Raihana Zakiya
logo: "/images/WhatsApp Image 2021-12-12 at 19.26.13.jpeg?raw=true"
description: > 
   I am currently undergoing the 6th semester at Padjadjaran University.  
   <br><br>
   I have interest to data analytics and financial analytics. I love and enjoy learning new things and would like to put my knowledge to good use.
   <br><br>
   <a href="https://www.linkedin.com/in/rina-raihana-zakiya-a101a3219/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 #your Google Analytics tracking ID here
