title: Rina Raihana Zakiya
logo: "/images/profile.jpeg?raw=true"
description: > 
   I am a fresh graduate from the Department of Statistics, with a profound enthusiasm for data analysis.
   <br><br>
    I am eager to contribute my skills and passion to your organization's data-driven initiatives. I am passionate about the fields of data entry, data analysis, and data visualization, where I am eager to apply my educational foundation and contribute to impactful insights. Proficient in statistical software such as Microsoft excel, R, Python and SQL to extract meaningful insights from data sets. In addition, I also have skills in data visualization, utilizing tools such as Tableau, Google Data Studio and Canva to create visually appealing representations.
   <br><br>
   <a href="https://www.linkedin.com/in/rina-raihana-zakiya-a101a3219/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 #your Google Analytics tracking ID here
