title: Rina Raihana Zakiya
logo: "/images/profile.jpeg?raw=true"
description: > 
   I am a fresh graduate from the Department of Statistics, with a profound enthusiasm for data analysis.
   <br><br>
     to impactful Proficient in statistical software such as Microsoft excel, R, Python, SQL, Tableau, Google Data Studio and Canva.
   <br><br>
   <a href="https://www.linkedin.com/in/rina-raihana-zakiya-a101a3219/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 #your Google Analytics tracking ID here
